#!/usr/bin/env bash

PREFIX=$(basename $(pwd))
ID=$(docker ps --filter "name=${PREFIX}_postgres" --format "{{.ID}}")
if [ -z "$ID" ]; then
  echo "Postgres container not found"
  exit 1
fi
docker exec -it $ID psql -U postgres

